'use client';
import { AlertTriangle, ArrowLeft, Bot, Check, CheckCircle2, ChevronRight, Clock3, Code2, ExternalLink, FileSearch, LoaderCircle, MessageSquareText, Send, ShieldCheck, TicketCheck, X } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { api } from '@/lib/api';

type Evidence={id:string;source_label:string;excerpt:string;line_start:number;line_end:number};
type Finding={id:string;issue_type:string;severity:string;confidence:number;service?:string;root_cause:string;rationale:string;evidence?:Evidence[]};
type Action={id:string;kind:string;destination:string;payload:Record<string,unknown>;payload_hash:string;status:string};
type Run={id:string;status:string;current_phase:string;created_at:string};
type Incident={id:string;title:string;description?:string;service?:string;environment?:string;status:string;severity?:string;files:{id:string;original_name:string;size:number;status:string}[];runs:Run[];findings:Finding[];actions:Action[];cookbook?:{markdown:string}};
type Event={id:number;phase:string;status:string;message:string;created_at:string};
const phases=['validate_upload','parse','classify','correlate','recommend','draft_actions','review','cookbook','complete'];

export default function IncidentWorkspace(){
  const params=useParams();const id=String(params.id);const [incident,setIncident]=useState<Incident|null>(null);const [events,setEvents]=useState<Event[]>([]);const [selected,setSelected]=useState<Finding|null>(null);const [tab,setTab]=useState<'findings'|'chat'|'cookbook'|'trace'>('findings');const [messages,setMessages]=useState<{role:string;content:string;citations?:{id:string;source:string}[]}[]>([]);const [question,setQuestion]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const refresh=()=>api<Incident>(`/incidents/${id}`).then(data=>{setIncident(data);setSelected(current=>current||data.findings[0]||null)}).catch(()=>location.href='/login');
  useEffect(()=>{refresh();api<typeof messages>(`/incidents/${id}/chat`).then(setMessages).catch(()=>{})},[id]);
  useEffect(()=>{const run=incident?.runs[0];if(!run||['completed','awaiting_approval','failed','cancelled'].includes(run.status))return;const timer=setInterval(refresh,1400);return()=>clearInterval(timer)},[incident?.runs?.[0]?.status]);
  useEffect(()=>{const runId=incident?.runs[0]?.id;if(!runId)return;let closed=false,last=0;async function poll(){while(!closed){try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL||'http://localhost:8010/api/v1'}/runs/${runId}/events`,{credentials:'include',headers:last?{'Last-Event-ID':String(last)}:{}});if(response.ok&&response.body){const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';while(!closed){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split('\n\n');buffer=blocks.pop()||'';for(const block of blocks){const line=block.split('\n').find(x=>x.startsWith('data: '));if(line){const event=JSON.parse(line.slice(6));last=event.id;setEvents(current=>current.some(e=>e.id===event.id)?current:[...current,event])}}}}}catch{}if(!closed)await new Promise(r=>setTimeout(r,1500))}}poll();return()=>{closed=true}},[incident?.runs?.[0]?.id]);
  async function decide(action:Action,decision:'approve'|'reject'){setBusy(true);setError('');try{await api(`/actions/${action.id}/${decision}`,{method:'POST',body:JSON.stringify({payload_hash:action.payload_hash,comment:`${decision}d from incident workspace`})});await refresh()}catch(err){setError(err instanceof Error?err.message:'Action failed')}finally{setBusy(false)}}
  async function chat(event:FormEvent){event.preventDefault();if(!question.trim())return;const text=question;setQuestion('');setMessages(x=>[...x,{role:'user',content:text}]);try{const answer=await api<{content:string;citations:{id:string;source:string}[]}>(`/incidents/${id}/chat`,{method:'POST',body:JSON.stringify({content:text})});setMessages(x=>[...x,{role:'assistant',content:answer.content,citations:answer.citations}])}catch(err){setError(err instanceof Error?err.message:'Chat unavailable')}}
  if(!incident)return <AppShell title="Loading incident"><div className="page-loading"><LoaderCircle className="spin"/>Retrieving incident state…</div></AppShell>;
  const run=incident.runs[0];
  return <AppShell title={incident.title} eyebrow={`INCIDENT // ${incident.id.slice(0,8).toUpperCase()}`} actions={<span className={`incident-status ${incident.severity||'low'}`}><i/>{incident.severity||'unclassified'} · {incident.status.replace('_',' ')}</span>}>
    <div className="back-row"><a href="/app"><ArrowLeft/>Operational overview</a><span>{incident.service||'Unassigned service'} · {incident.environment||'Unknown environment'} · {incident.files.length} file(s)</span></div>
    <section className="live-workflow"><div className="workflow-heading"><div><span className="kicker">LIVE ORCHESTRATION</span><h2>{run?.status==='awaiting_approval'?'Analysis complete — review required':run?.status==='failed'?'Analysis partially failed':'Agents are analyzing evidence'}</h2></div><span><Clock3/>Run {run?.id.slice(0,8)}</span></div><div className="live-rail">{phases.map((phase,index)=>{const evt=[...events].reverse().find(e=>e.phase===phase);const complete=index<phases.indexOf(run?.current_phase||'')||evt?.status==='completed';const active=phase===run?.current_phase;return <div key={phase} className={`${complete?'complete':''} ${active?'active':''}`}><span>{complete?<Check size={14}/>:active?<LoaderCircle size={14} className="spin"/>:index+1}</span><b>{phase.replace('_',' ')}</b>{index<phases.length-1&&<ChevronRight/>}</div>})}</div><div className="event-console">{events.slice(-3).map(event=><p key={event.id}><time>{new Date(event.created_at).toLocaleTimeString()}</time><b>{event.phase}</b><span>{event.message}</span></p>)}{!events.length&&<p><LoaderCircle className="spin"/><span>Connecting to persisted workflow events…</span></p>}</div></section>
    <nav className="incident-tabs" aria-label="Incident workspace sections">{(['findings','chat','cookbook','trace'] as const).map(name=><button className={tab===name?'active':''} onClick={()=>setTab(name)} key={name}>{name==='findings'?<FileSearch/>:name==='chat'?<MessageSquareText/>:name==='cookbook'?<Code2/>:<Bot/>}{name}</button>)}</nav>
    {error&&<div className="form-error global-error" role="alert">{error}</div>}
    {tab==='findings'&&<section className="findings-layout"><div className="findings-list"><div className="filter-bar"><b>{incident.findings.length} findings</b><span>Severity</span><span>Service</span><span>Confidence</span></div>{incident.findings.length?incident.findings.map(f=><button key={f.id} onClick={()=>setSelected(f)} className={selected?.id===f.id?'selected':''}><span className={`severity-badge ${f.severity}`}>{f.severity}</span><div><h3>{f.root_cause}</h3><p>{f.service||'Unknown service'} · {f.issue_type.replaceAll('_',' ')}</p></div><strong>{Math.round(f.confidence*100)}%</strong><ChevronRight/></button>):<div className="empty-command"><CheckCircle2/><h3>No actionable issues detected</h3><p>The analysis completed without evidence strong enough to create a finding.</p></div>}</div>{selected&&<aside className="finding-detail"><div className="finding-top"><span className={`severity-badge ${selected.severity}`}>{selected.severity}</span><strong>{Math.round(selected.confidence*100)}% confidence</strong></div><h2>{selected.root_cause}</h2><p>{selected.rationale}</p><div className="detail-block"><span>PROBABLE ROOT CAUSE</span><p>{selected.root_cause}. Treat this as a hypothesis until a responder validates system state.</p></div><div className="detail-block"><span>DETECTION EVIDENCE</span>{selected.evidence?.map(e=><article key={e.id}><code>{e.source_label}</code><pre>{e.excerpt}</pre><small>Content hash · exact line provenance retained</small></article>)||<p>Open this finding through the filtered findings API to retrieve evidence.</p>}</div><div className="risk-callout"><AlertTriangle/><p><b>Human validation required</b>Recommendations are suggestions only; no command has been executed.</p></div></aside>}</section>}
    {tab==='chat'&&<section className="chat-panel"><div className="chat-head"><div><MessageSquareText/><span><b>Incident AI</b><small>Answers are isolated to this incident</small></span></div><em><ShieldCheck/>Evidence citations required</em></div><div className="message-list">{messages.length?messages.map((message,index)=><article className={message.role} key={index}><span>{message.role==='assistant'?'AI':'YOU'}</span><p>{message.content}</p>{message.citations?.map(c=><button className="citation-button" key={c.id} onClick={()=>setTab('findings')}>{c.source}<ExternalLink/></button>)}</article>):<div className="chat-empty"><Bot/><h3>Ask this incident, not the internet</h3><p>Try “What is the most likely root cause?” or “Show evidence for this recommendation.”</p></div>}</div><form className="chat-form" onSubmit={chat}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about evidence, chronology, root cause, or a safer rollback…"/><button aria-label="Send question"><Send/></button></form></section>}
    {tab==='cookbook'&&<section className="cookbook-panel">{incident.cookbook?<><div className="cookbook-head"><div><span className="kicker">RESPONSE COOKBOOK</span><h2>Reviewed suggestions, ready for operators</h2></div><a className="app-cta" href={`${process.env.NEXT_PUBLIC_API_URL||'http://localhost:8010/api/v1'}/incidents/${id}/cookbook.md`}><Code2/>Export Markdown</a></div><pre>{incident.cookbook.markdown}</pre></>:<div className="empty-command"><LoaderCircle/><h3>Cookbook is being synthesized</h3><p>It will appear after findings and remediation recommendations are consolidated.</p></div>}</section>}
    {tab==='trace'&&<section className="trace-panel"><div className="card-title"><div><span>AGENT & TOOL ACTIVITY</span><h2>Persisted execution trace</h2></div><Bot/></div>{events.map(event=><div key={event.id}><span className={event.status}/><time>{new Date(event.created_at).toLocaleString()}</time><b>{event.phase.replace('_',' ')}</b><p>{event.message}</p></div>)}</section>}
    {incident.actions.length>0&&<section className="approval-dock"><div><span className="kicker">HUMAN APPROVAL CHECKPOINT</span><h2>External actions are waiting</h2><p>Approve or reject the exact immutable payload. Delivery uses the mock sandbox adapter.</p></div><div>{incident.actions.map(action=><article key={action.id}><span className="action-kind">{action.kind==='slack'?<MessageSquareText/>:<TicketCheck/>}{action.kind} → {action.destination}</span><pre>{JSON.stringify(action.payload,null,2)}</pre><footer>{action.status==='pending'?<><button disabled={busy} onClick={()=>decide(action,'reject')} className="reject"><X/>Reject</button><button disabled={busy} onClick={()=>decide(action,'approve')} className="approve"><Check/>Approve & deliver</button></>:<span className={`delivered ${action.status}`}><CheckCircle2/>{action.status}</span>}</footer></article>)}</div></section>}
  </AppShell>
}
