'use client';
import { AlertTriangle, ArrowLeft, Bot, Check, CheckCircle2, ChevronRight, Clock3, Code2, ExternalLink, FileSearch, LoaderCircle, MessageSquareText, Send, ShieldCheck, TicketCheck, UserCheck, X } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { api, streamApi } from '@/lib/api';

type Evidence={id:string;source_label:string;excerpt:string;line_start:number;line_end:number};
type Finding={id:string;issue_type:string;severity:string;confidence:number;service?:string;root_cause:string;rationale:string;evidence?:Evidence[]};
type Action={id:string;kind:string;destination:string;payload:Record<string,unknown>;payload_hash:string;status:string};
type Run={id:string;status:string;current_phase:string;started_at?:string;completed_at?:string;created_at:string};
type Incident={id:string;title:string;description?:string;service?:string;environment?:string;status:string;severity?:string;files:{id:string;original_name:string;size:number;status:string}[];runs:Run[];findings:Finding[];actions:Action[];cookbook?:{markdown:string}};
type Event={id:number;phase:string;status:string;message:string;created_at:string};
type Integration={provider:string;mode:string;status:string;available:boolean;destination?:string};
const phases=['validate_upload','parse','classify','correlate','recommend','draft_actions','review','cookbook','complete'];
function runTime(run?:Run){if(!run?.started_at)return 'Queued';const elapsed=Math.max(0,Date.parse(run.completed_at||new Date().toISOString())-Date.parse(run.started_at));const seconds=Math.floor(elapsed/1000);const minutes=Math.floor(seconds/60);return minutes?`${minutes}m ${String(seconds%60).padStart(2,'0')}s`:`${seconds}s`}
function runTimingLabel(run?:Run){if(run?.completed_at)return `Completed at ${new Date(run.completed_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;return run?.started_at?`Elapsed ${runTime(run)}`:'Queued'}
function payloadText(value:unknown){return typeof value==='string'||typeof value==='number'||typeof value==='boolean'?String(value):'—'}
function ActionPayload({action}:{action:Action}){const lines=action.kind==='slack'?payloadText(action.payload.text).replace(' · Confidence:','\nConfidence:').split('\n'):action.kind==='jira'?[`Summary: ${payloadText(action.payload.summary)}`,`Description: ${payloadText(action.payload.description)}`,`Priority: ${payloadText(action.payload.priority)}`,`Labels: ${Array.isArray(action.payload.labels)?action.payload.labels.map(payloadText).join(', '):payloadText(action.payload.labels)}`]:Object.entries(action.payload).map(([key,value])=>`${key}: ${payloadText(value)}`);return <div className="action-message">{lines.map((line,index)=>{const separator=line.indexOf(':');const value=separator>0?line.slice(separator+1).trim():'';return separator>0?<p className={value?'':'action-section-heading'} key={index}><b>{line.slice(0,separator)}:</b>{value&&<span>{value}</span>}</p>:<strong key={index}>{line}</strong>})}</div>}
function CookbookContent({markdown,checked,onToggle}:{markdown:string;checked:Set<number>;onToggle:(index:number)=>void}){return <div className="cookbook-content">{markdown.split('\n').map((line,index)=>{if(line.startsWith('# '))return <h2 key={index}>{line.slice(2)}</h2>;if(line.startsWith('## '))return <h3 key={index}>{line.slice(3)}</h3>;if(line.startsWith('> '))return <aside key={index}>{line.slice(2)}</aside>;if(line.startsWith('- [ ] '))return <label className="cookbook-check" key={index}><input type="checkbox" checked={checked.has(index)} onChange={()=>onToggle(index)}/><span>{line.slice(6)}</span></label>;if(line.startsWith('- '))return <div className="cookbook-bullet" key={index}><i/>{line.slice(2)}</div>;if(!line.trim())return <div className="cookbook-space" key={index}/>;return <p key={index}>{line.replaceAll('`','')}</p>})}</div>}

export default function IncidentWorkspace(){
  const params=useParams();const id=String(params.id);const [incident,setIncident]=useState<Incident|null>(null);const [events,setEvents]=useState<Event[]>([]);const [selected,setSelected]=useState<Finding|null>(null);const [tab,setTab]=useState<'findings'|'chat'|'cookbook'|'trace'>('findings');const [messages,setMessages]=useState<{role:string;content:string;citations?:{id:string;source:string}[]}[]>([]);const [integrations,setIntegrations]=useState<Integration[]|null>(null);const [cookbookChecks,setCookbookChecks]=useState<Set<number>>(()=>new Set());const [question,setQuestion]=useState('');const [busy,setBusy]=useState(false);const [statusBusy,setStatusBusy]=useState(false);const [error,setError]=useState('');
  const refresh=()=>api<Incident>(`/incidents/${id}`).then(data=>{setIncident(data);setSelected(current=>current||data.findings[0]||null)}).catch(()=>location.href='/login');
  useEffect(()=>{refresh();api<typeof messages>(`/incidents/${id}/chat`).then(setMessages).catch(()=>{});const refreshIntegrations=()=>api<Integration[]>('/integrations?verify=true').then(setIntegrations).catch(()=>setIntegrations([]));refreshIntegrations();const syncIntegrations=()=>{if(document.visibilityState==='visible')refreshIntegrations()};document.addEventListener('visibilitychange',syncIntegrations);window.addEventListener('focus',refreshIntegrations);return()=>{document.removeEventListener('visibilitychange',syncIntegrations);window.removeEventListener('focus',refreshIntegrations)}},[id]);
  useEffect(()=>{const run=incident?.runs[0];if(!run||['completed','failed','cancelled'].includes(run.status))return;const timer=setInterval(refresh,1400);return()=>clearInterval(timer)},[incident?.runs?.[0]?.status]);
  useEffect(()=>{const run=incident?.runs[0];const runId=run?.id;if(!runId)return;const terminal=['completed','failed','cancelled'].includes(run.status);let closed=false,last=0;async function poll(){while(!closed){try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL||'http://localhost:8010/api/v1'}/runs/${runId}/events`,{credentials:'include',headers:last?{'Last-Event-ID':String(last)}:{}});if(response.ok&&response.body){const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';while(!closed){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split('\n\n');buffer=blocks.pop()||'';for(const block of blocks){const line=block.split('\n').find(x=>x.startsWith('data: '));if(line){const event=JSON.parse(line.slice(6));last=event.id;setEvents(current=>current.some(e=>e.id===event.id)?current:[...current,event])}}}}}catch{}if(terminal)break;if(!closed)await new Promise(r=>setTimeout(r,1500))}}poll();return()=>{closed=true}},[incident?.runs?.[0]?.id,incident?.runs?.[0]?.status]);
  async function decide(action:Action,decision:'approve'|'reject'){setBusy(true);setError('');try{await api(`/actions/${action.id}/${decision}`,{method:'POST',body:JSON.stringify({payload_hash:action.payload_hash,comment:`${decision}d from incident workspace`})});await refresh()}catch(err){setError(err instanceof Error?err.message:'Action failed')}finally{setBusy(false)}}
  async function chat(event:FormEvent){event.preventDefault();if(!question.trim()||busy)return;const text=question;setQuestion('');setError('');setBusy(true);setMessages(x=>[...x,{role:'user',content:text},{role:'assistant',content:''}]);try{await streamApi(`/incidents/${id}/chat`,{method:'POST',body:JSON.stringify({content:text})},(event,data)=>{if(event==='token'){const content=typeof data.content==='string'?data.content:'';setMessages(items=>items.map((item,index)=>index===items.length-1?{...item,content:item.content+content}:item))}if(event==='complete')setMessages(items=>items.map((item,index)=>index===items.length-1?{...item,citations:data.citations as {id:string;source:string}[]}:item));if(event==='error')throw new Error(typeof data.detail==='string'?data.detail:'Chat unavailable')})}catch(err){setMessages(items=>items.filter((item,index)=>index!==items.length-1||item.content));setError(err instanceof Error?err.message:'Chat unavailable')}finally{setBusy(false)}}
  async function toggleIncidentStatus(){if(!incident||statusBusy)return;const nextStatus=incident.status==='resolved'?'active':'resolved';setStatusBusy(true);setError('');try{const result=await api<{status:'active'|'resolved';event:Event|null}>(`/incidents/${id}/status`,{method:'PATCH',body:JSON.stringify({status:nextStatus})});setIncident(current=>current?{...current,status:result.status}:current);if(result.event)setEvents(current=>current.some(event=>event.id===result.event?.id)?current:[...current,result.event as Event])}catch(err){setError(err instanceof Error?err.message:'Unable to update incident status')}finally{setStatusBusy(false)}}
  if(!incident)return <AppShell title="Loading incident"><div className="page-loading"><LoaderCircle className="spin"/>Retrieving incident state…</div></AppShell>;
  const run=incident.runs[0];
  const latestCurrentPhaseEvent=[...events].reverse().find(event=>event.phase===run?.current_phase);
  const currentEventId=run?.status==='running'&&latestCurrentPhaseEvent?.status==='running'?latestCurrentPhaseEvent.id:undefined;
  const pendingActions=incident.actions.filter(action=>action.status==='pending');
  const reviewWaiting=pendingActions.length>0;
  const incidentResolved=incident.status==='resolved';
  const noIntegrationsAvailable=integrations!==null&&!integrations.some(item=>item.available);
  const slackDestination=integrations?.find(item=>item.provider==='slack'&&item.available)?.destination;
  const toggleCookbookCheck=(index:number)=>setCookbookChecks(current=>{const next=new Set(current);if(next.has(index))next.delete(index);else next.add(index);return next});
  return <AppShell title={incident.title} eyebrow={`INCIDENT // ${incident.id.slice(0,8).toUpperCase()}`} actions={<div className="incident-meta-actions"><span className={`criticality-indicator ${incident.severity||'low'}`}><i/>Severity: {incident.severity||'unclassified'}</span><button type="button" className={`incident-status-toggle ${incidentResolved?'resolved':'active'}`} aria-pressed={incidentResolved} aria-label={`Mark incident as ${incidentResolved?'active':'resolved'}`} disabled={statusBusy} onClick={toggleIncidentStatus}><i/><span>{statusBusy?'Updating…':incidentResolved?'RESOLVED':'ACTIVE'}</span></button></div>}>
    <div className="back-row"><a href="/app"><ArrowLeft/>Operational overview</a><span>{incident.service||'Unassigned service'} · {incident.environment||'Unknown environment'} · {incident.files.length} file(s)</span></div>
    <section className="live-workflow"><div className="workflow-heading"><div className="workflow-status-line"><span className="kicker">LIVE WORKFLOW</span><i aria-hidden="true">:</i><h2>{reviewWaiting?'Analysis complete — review required':run?.status==='completed'?'Analysis and review complete':run?.status==='awaiting_approval'?'Analysis complete — review required':run?.status==='failed'?'Analysis partially failed':run?.status==='cancelled'?'Analysis cancelled':'Agents are analyzing evidence'}</h2></div><span><Clock3/>{runTimingLabel(run)}</span></div><div className="live-rail">{phases.map((phase,index)=>{const evt=[...events].reverse().find(e=>e.phase===phase);const terminal=phase==='complete'&&run?.status==='completed';const heldForReview=reviewWaiting&&index>=phases.indexOf('review');const complete=!heldForReview&&(terminal||index<phases.indexOf(run?.current_phase||'')||evt?.status==='completed');const active=reviewWaiting?phase==='review':!complete&&phase===run?.current_phase;const llmStage=['recommend','draft_actions','cookbook'].includes(phase);const stageIcon=llmStage?<Bot size={14} className={active?'stage-icon-processing':undefined} aria-label="LLM stage"/>:phase==='review'?<UserCheck size={14} aria-label="Human-in-the-loop stage"/>:null;return <div key={phase} className={`${complete?'complete':'incomplete'} ${active?'active':''} ${stageIcon?'special-stage':''}`} aria-current={active?'step':undefined}><span>{stageIcon||(complete?<Check size={14}/>:active?<LoaderCircle size={14} className="spin" aria-label={`${phase.replace('_',' ')} is processing`}/>:index+1)}</span><b>{phase.replace('_',' ')}</b>{index<phases.length-1&&<ChevronRight/>}</div>})}</div><div className="event-console">{events.slice(-3).map(event=><p key={event.id} className={event.id===currentEventId?'current-stage':''}><time>{new Date(event.created_at).toLocaleTimeString()}</time><b>{event.phase}</b><span>{event.message}</span></p>)}{!events.length&&<p><LoaderCircle className="spin"/><span>Connecting to persisted workflow events…</span></p>}</div></section>
    <nav className="incident-tabs" aria-label="Incident workspace sections">{(['findings','chat','cookbook','trace'] as const).map(name=><button className={`${tab===name?'active':''} ${name==='chat'?'ai-chat-tab':''}`} onClick={()=>setTab(name)} key={name}>{name==='findings'?<FileSearch/>:name==='chat'?<MessageSquareText/>:name==='cookbook'?<Code2/>:<Bot/>}{name==='chat'?'AI Chat':name}</button>)}</nav>
    {error&&<div className="form-error global-error" role="alert">{error}</div>}
    {tab==='findings'&&<section className="findings-layout"><div className="findings-list"><div className="filter-bar"><b>{incident.findings.length} findings</b><span>Severity</span><span>Service</span><span>Confidence</span></div>{incident.findings.length?incident.findings.map(f=><button key={f.id} onClick={()=>setSelected(f)} className={selected?.id===f.id?'selected':''}><span className={`severity-badge ${f.severity}`}>{f.severity}</span><div><h3>{f.root_cause}</h3><p>{f.service||'Unknown service'} · {f.issue_type.replaceAll('_',' ')}</p></div><strong>{Math.round(f.confidence*100)}%</strong><ChevronRight/></button>):<div className="empty-command"><CheckCircle2/><h3>No actionable issues detected</h3><p>The analysis completed without evidence strong enough to create a finding.</p></div>}</div>{selected&&<aside className="finding-detail"><div className="finding-top"><span className={`severity-badge ${selected.severity}`}>{selected.severity}</span><strong>{Math.round(selected.confidence*100)}% confidence</strong></div><h2>{selected.root_cause}</h2><p>{selected.rationale}</p><div className="detail-block"><span>PROBABLE ROOT CAUSE</span><p>{selected.root_cause}. Treat this as a hypothesis until a responder validates system state.</p></div><div className="detail-block"><span>DETECTION EVIDENCE</span>{selected.evidence?.map(e=><article key={e.id}><code>{e.source_label}</code><pre>{e.excerpt}</pre><small>Content hash · exact line provenance retained</small></article>)||<p>Open this finding through the filtered findings API to retrieve evidence.</p>}</div><div className={`risk-callout ${incidentResolved?'complete':''}`}>{incidentResolved?<ShieldCheck/>:<AlertTriangle/>}<p><b>{incidentResolved?'Human validation complete':'Human validation required'}</b>{incidentResolved?'A responder has marked this incident as resolved.':'This incident remains active and requires responder validation.'}</p></div></aside>}</section>}
    {tab==='chat'&&<section className="chat-panel"><div className="chat-head"><div><MessageSquareText/><span><b>Incident AI</b><small>Answers are isolated to this incident</small></span></div><em><ShieldCheck/>Evidence citations required</em></div><div className="message-list">{messages.length?messages.map((message,index)=><article className={message.role} key={index}><span>{message.role==='assistant'?'AI':'YOU'}</span><p>{message.content}{busy&&index===messages.length-1&&<span className="streaming-cursor" aria-label="Generating"/>}</p>{message.citations?.map(c=><button className="citation-button" key={c.id} onClick={()=>setTab('findings')}>{c.source}<ExternalLink/></button>)}</article>):<div className="chat-empty"><Bot/><h3>Ask this incident, not the internet</h3><p>Try “What is the most likely root cause?” or “Show evidence for this recommendation.”</p></div>}</div><form className="chat-form" onSubmit={chat}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about evidence, chronology, root cause, or a safer rollback…" disabled={busy}/><button aria-label="Send question" disabled={busy}><Send/></button></form></section>}
    {tab==='cookbook'&&<section className="cookbook-panel">{incident.cookbook?<><div className="cookbook-head"><div><span className="kicker">RESPONSE COOKBOOK</span><h2>Reviewed suggestions, ready for operators</h2></div><a className="app-cta" href={`${process.env.NEXT_PUBLIC_API_URL||'http://localhost:8010/api/v1'}/incidents/${id}/cookbook.md`}><Code2/>Export Markdown</a></div><CookbookContent markdown={incident.cookbook.markdown} checked={cookbookChecks} onToggle={toggleCookbookCheck}/></>:<div className="empty-command"><LoaderCircle/><h3>Cookbook is being synthesized</h3><p>It will appear after findings and remediation recommendations are consolidated.</p></div>}</section>}
    {tab==='trace'&&<section className="trace-panel"><div className="card-title"><div><span>AGENT & TOOL ACTIVITY</span><h2>Persisted execution trace</h2></div><Bot/></div>{events.map(event=><div key={event.id} className={event.id===currentEventId?'current-stage':''}><span className={event.status}/><time>{new Date(event.created_at).toLocaleString()}</time><b>{event.phase.replace('_',' ')}</b><p>{event.message}</p></div>)}</section>}
    {incident.actions.length>0&&<section className="approval-dock"><div><span className="kicker">{noIntegrationsAvailable?'PREVIEW ONLY':pendingActions.length?'HUMAN APPROVAL CHECKPOINT':'ACTION REVIEW COMPLETE'}</span><h2>{noIntegrationsAvailable?'Integration not available':pendingActions.length?'External actions are waiting':'All external actions reviewed'}</h2><p>{noIntegrationsAvailable?'Neither Slack nor Jira is available. Proposed actions are shown for reference until an integration is configured and connected.':pendingActions.length?`${pendingActions.length} action${pendingActions.length===1?'':'s'} still require a decision. Approve or reject each immutable payload.`:'Every available proposed external action has been approved or rejected. No further review is required.'}</p></div><div>{incident.actions.map(action=>{const unavailable=action.status==='unavailable'||!(integrations?.some(item=>item.provider===action.kind&&item.available)??false);const destination=action.kind==='slack'&&slackDestination?slackDestination:action.destination;return <article key={action.id} className={unavailable?'unavailable':''}><span className="action-kind">{action.kind==='slack'?<MessageSquareText/>:<TicketCheck/>}{action.kind} → {destination}</span><ActionPayload action={action}/><footer>{action.status==='pending'?<><button disabled={busy} onClick={()=>decide(action,'reject')} className="reject"><X/>Reject</button>{unavailable?<button className="not-available" disabled>Integration Not Available</button>:<button disabled={busy} onClick={()=>decide(action,'approve')} className="approve"><Check/>Approve & deliver</button>}</>:action.status==='unavailable'?<button className="not-available" disabled>Integration Not Available</button>:<span className={`delivered ${action.status}`}><CheckCircle2/>{action.status}</span>}</footer></article>})}</div></section>}
  </AppShell>
}
