'use client';
import { ArrowRight, LockKeyhole, Network, ShieldCheck } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { api } from '@/lib/api';

export function AuthForm({mode}:{mode:'login'|'signup'}){
  const signup=mode==='signup';const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setBusy(true);const form=new FormData(event.currentTarget);try{await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify({email:form.get('email'),password:form.get('password'),...(signup?{display_name:form.get('name')}:{})})});location.href='/app'}catch(err){setError(err instanceof Error?err.message:'Unable to continue')}finally{setBusy(false)}}
  return <main className="auth-page"><a className="brand auth-brand" href="/"><span className="brand-mark"><Network size={19}/></span><span>DevOps <em>IAS</em></span></a><section className="auth-card"><div className="eyebrow"><span/> SECURE WORKSPACE ACCESS</div><h1>{signup?'Create your incident workspace':'Return to incident command'}</h1><p>{signup?'The first account becomes workspace Admin. Additional accounts join as Responders.':'Continue reviewing evidence, approvals, and active analysis runs.'}</p><form onSubmit={submit}>{signup&&<label>Display name<input name="name" required minLength={2} autoComplete="name" placeholder="Grace Operator"/></label>}<label>Email address<input name="email" type="email" required autoComplete="email" placeholder="you@company.com"/></label><label>Password<input name="password" type="password" minLength={12} required autoComplete={signup?'new-password':'current-password'} placeholder="12 characters minimum"/></label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="pill-button auth-submit" disabled={busy}>{busy?'Securing session…':signup?'Create workspace':'Log in'}<span className="button-icon"><ArrowRight size={18}/></span></button></form><div className="auth-switch">{signup?'Already have access?':'New to the suite?'} <a href={signup?'/login':'/signup'}>{signup?'Log in':'Create an account'}</a></div></section><div className="auth-proof"><span><LockKeyhole/>HttpOnly sessions</span><span><ShieldCheck/>Argon2id passwords</span><span><Network/>Workspace isolation</span></div></main>
}
